services:
  mood-app:
    container_name: mood-app
    image: hb0730/mood:latest
    ports:
      - 3000:3000
    volumes:
      - ./prisma/db:/app/prisma/db
    environment:
      - DATABASE_URL=file:/app/prisma/db/mood.db
      - JWT_SECRET=your-secret-key
      - ADMIN_PASSWORD=admin123
    restart: always
