version: '3.8'

services:
  mood-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - DATABASE_URL=file:./prisma/db/dev.db
      - JWT_SECRET=${JWT_SECRET:-your-dev-jwt-secret-key}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      # 数据库文件持久化
      - mood_data:/app/prisma/db
      # 日志持久化
      - mood_logs:/app/logs
    networks:
      - mood-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # 开发环境数据库管理（可选）
  prisma-studio:
    image: node:20.19.4-alpine
    container_name: mood-prisma-studio
    restart: "no"
    ports:
      - "5555:5555"
    working_dir: /app
    volumes:
      - mood_data:/app/prisma/db
      - ./prisma:/app/prisma:ro
    command: >
      sh -c "
        npm install -g prisma &&
        prisma studio --hostname 0.0.0.0 --port 5555
      "
    profiles:
      - dev-tools

networks:
  mood-network:
    driver: bridge

volumes:
  mood_data:
    driver: local
  mood_logs:
    driver: local
