services:
  # 数据库初始化服务
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRISMA_SCHEMA: /app/prisma/schema.prisma
    image: mood-ssr:latest
    container_name: mood-db-init
    restart: "no"
    environment:
      - DATABASE_URL=file:/app/prisma/db/prod.db
      - PRISMA_SCHEMA=/app/prisma/schema.prisma
      - RUN_MIGRATIONS=true
    volumes:
      - ./db:/app/prisma/db
    command: >
      sh -c "
        echo 'Starting database initialization...' &&
        mkdir -p /app/prisma/db &&
        npx prisma migrate deploy --schema=$PRISMA_SCHEMA ||
        npx prisma db push --schema=$PRISMA_SCHEMA &&
        echo 'Database initialization completed'
      "

  # 主应用服务
  mood-app:
    image: mood-ssr:latest
    container_name: mood-app
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/db/prod.db
      - PRISMA_SCHEMA=/app/prisma/schema.prisma
    volumes:
      - ./db:/app/prisma/db
    restart: unless-stopped
