version: '3.8'

services:
  mood-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mood-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mood-network
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-dev-jwt-secret-key}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      # 日志持久化
      - mood_logs:/app/logs
    networks:
      - mood-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # 开发环境Nginx配置
  nginx:
    image: nginx:alpine
    container_name: mood-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - mood_logs:/var/log/nginx
    depends_on:
      - mood-app
    networks:
      - mood-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

networks:
  mood-network:
    driver: bridge

volumes:
  mood_logs:
    driver: local
